baseURL = "https://janson-ig.github.io/janson_profile/"

languageCode = "en"
defaultContentLanguage = "en"

title = "Janson"
#copyright = ""

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Janson"
  headline = "You forget a thousand things every day,How about you make sure this is one of them?"
  image = "img/me.jpg"

  links = [
    { github = "https://github.com/Janson-ig" },
    { leetcode = { href = "https://leetcode.cn/u/spongenoob/", text = "LeetCode" } },
    { twitter = "https://twitter.com/wang_0902" },
    { linkedin = "https://www.linkedin.com/in/%E5%BB%BA%E5%B5%A9-%E7%8E%8B-a96704163/" },
    { weibo = { href = "https://weibo.com/u/3687367955", text = "weibo" } },

  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86"
